name: Build Windows Executable

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Upload Windows Build
        uses: actions/upload-artifact@v3
        with:
          name: VetApp_Windows_Release
          path: build\windows\x64\runner\Release\